config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'home', to: 'pages#home'
  get 'coaching', to: 'pages#coaching'
  get 'ebook', to: 'pages#ebook'
  get 'start_now', to: 'pages#start_now'
  get 'about', to: 'pages#about'
  # get 'index', to: 'pages#index' #blog access

  root to: "posts#index"
  resources :posts

  resources "contacts", only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "alexandre.deniau@outlook.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  def self.search(search)
    where("title LIKE ?", "%#{search}%")
    where("body LIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create, :new]
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
      redirect_to root_path
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :ebook, :contact, :start_now, :coaching, :index, :about]

  def home
  end

  def contact
  end

  def about
  end

  def start_now
  end

  def ebook
  end

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :delete]
   skip_before_action :authenticate_user!, only: [:index, :show]
  # Index action to render all posts
  def index
    @posts = Post.all
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order('created_at DESC')
    end
  end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    @post = Post.new
    if @post.save(post_params)
      @post.update_attributes(post_params)
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
  end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="banner-parallax-4">
<div class="col-xs-10 col-xs-offset-1 col-sm-5 col-sm-offset-2">
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true  %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>
</div>
</div

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="title" content="Hollistic Wellness Coach" >
    <title>TODO // Sandrine</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
     <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Fira+Sans|Lato|Raleway|Roboto|Satisfy" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="b68173b6-5d79-4693-bf90-ef6604053ae9";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>
    <%= favicon_link_tag "logohead.png" %>

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="banner-parallax-3">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">

      </div>
    </div>
  </div>
</div>

app/views/pages/coaching.html.erb
<div class="transpa">

</div>

app/views/pages/ebook.html.erb
<div class="transpa">
<i class="fa fa-book fa-5x" aria-hidden="true"></i>

</div>

app/views/pages/home.html.erb
<div class="container-fluid no-padding">
  <div class="banner">
    <div class="banner-content text-center parallax">
      <br>
      <br>
      <h1>
      <svg class="arrows">
      <path class="a1" d="M0 0 L30 32 L60 0"></path>
      <path class="a2" d="M0 20 L30 52 L60 20"></path>
      <path class="a3" d="M0 40 L30 72 L60 40"></path>
      </svg>
      </h1>
    </div>
  </div>
  <div class="banner-parallax-1" id="sandrine-text">
    <div class="row-eq-height">
      <div class="col-xs-12 col-md-10 col-md-offset-1 text-center">
        <div class="texte-sandrine">
          <h3 >Dear visitors, Welcome</h3>
          <br>
          <h5>"Kindness is always fashionable, and always welcome." </h5> <br><p>Amelia Barr</p>
          <i class="fa fa-angle-double-down fa-3x" aria-hidden="true"></i>
        </div>
      </div>
    </div>
  </div>
  <div class="banner-parallax-1" id="sandrine-text">
    <div class="row-eq-height" id="text2">
      <div class="col-xs-12 col-md-8 col-md-offset-10 text-center">
        <div  class="texte-sandrine">
          <h3 >I hope you guys will enjoy visiting my brand-new website</h3>
          <br>
          <h5>Further down you 'll find a description of myself and what I can teach you </h5> <br><p>Sandrine Loiret</p>
          <i class="fa fa-angle-double-down fa-3x" aria-hidden="true"></i>
        </div>
      </div>
    </div>
  </div>
  <div id="the-number-four" class="container-fluid">
    <div class="row text-center hidden-xs hidden-sm alignement-texte">
      <div id="relation" class="col-xs-12 col-md-6 no-padding blur">
        <div class="case-1 case-01">
          <h3>Relation</h3>
        </div>
      </div>
      <div id="bodyhealth" class="col-xs-12 col-md-6 no-padding blur">
        <div class="case-1 case-02">
          <h3>Body-health</h3>
        </div>
      </div>
      <div id="nutrition" class="col-xs-12 col-md-6 no-padding blur">
        <div class="case-1 case-03">
          <h3>Nutrition</h3>
        </div>
      </div>
      <div id="selfesteem" class="col-xs-12 col-md-6 no-padding blur">
        <div class="case-1 case-04">
          <h3>Self-Esteem</h3>
        </div>
      </div>
    </div>
    <div class="row-eq-height">
      <div class="border-texte">
        <div class="texte-sandrine-alpha hidden-xs hidden-sm">
          <div id="avatar1" class="avatar"></div>
          <h3 id="switchtitle">"Je m'appelle Sandrine"</h3>
          <br>
          <h5 id="switchparag">J'ai suivi la formation de psychanalyste/psychothérapeute intégratif à la Nouvelle Faculté Libre à Paris. J'ai donc une approche dite Intégrative fondée sur la phénoménologie et l existentialisme une approche dite humaniste-existentielle. La thérapie que je propose consiste à consolider la capacité de chacun à exprimer ses difficultés, repérer ses blocages, ce qui nous empêche de vivre librement en trouvant ses propres solutions en développant des changements qui nous permettent de faire nos choix, vos choix.
          </h5>
        </div>
      </div>
    </div>
  </div>
  <div id="the-number-four" class="container-fluid">
    <div class="row text-center hidden-md hidden-lg">
      <div id="selfesteem" class="dépad">
        <div class="case-1 case-05 ">
          <p style="padding: 10px; color: white"> J'ai suivi la formation de psychanalyste/psychothérapeute intégratif à la Nouvelle Faculté Libre à Paris. J'ai donc une approche dite Intégrative fondée sur la phénoménologie et l existentialisme une approche dite humaniste-existentielle. La thérapie que je propose consiste à consolider la capacité de chacun à exprimer ses difficultés, repérer ses blocages, ce qui nous empêche de vivre librement en trouvant ses propres solutions en développant des changements qui nous permettent de faire nos choix, vos choix.</p>
        </div>
      </div>
      <div id="relation" class=" dépad">
        <div class="case-1 case-01">
          <h3>Relation</h3>
        </div>
      </div>
      <div id="bodyhealth" class=" dépad">
        <div class="case-1 case-02">
          <h3>Body-health</h3>
        </div>
      </div>
      <div id="nutrition" class=" dépad">
        <div class="case-1 case-03">
          <h3>Nutrition</h3>
        </div>
      </div>
      <div id="selfesteem" class=" dépad">
        <div class="case-1 case-04">
          <h3>Self-Esteem</h3>
        </div>
      </div>
    </div>
  </div>
  <div class="banner-parallax-2">
    <div>
      <h4 class="text-center">"I've learned that people will forget what you saidpeople will forget what you did, <br>but people will never forget how you made them feel."</h4><br>
      <p class="text-center">Maya Angelou</p>
    </div>
  </div>
  <div id="the-why" class="container-fluid hidden-xs">
    <div class="row">
      <div class="why text-center">
        <div class="col-sm-6 col-md-3">
          <div class="newclass">
            <h3>What I do</h3>
            Being happy
            <br>
            <br>
            <i class="fa fa-question-circle fa-3x" aria-hidden="true"></i>
            <br>
            <br>
            <div class="btn btn-primary btn-md importz">Read more
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-3">
          <div class="newclass">
            <h3>What I offer you </h3>
            A way to be happy
            <br>
            <br>
            <i class="fa fa-lightbulb-o fa-3x" aria-hidden="true"></i>
            <br>
            <br>
            <div class="btn btn-primary btn-md importz">Contact me</div>
          </div>
        </div>
        <div class="col-sm-6 col-md-3">
          <div class="newclass">
            <h3>What I do</h3>
            Being happy
            <br>
            <br>
            <i class="fa fa-question-circle fa-3x" aria-hidden="true"></i>
            <br>
            <br>
            <div class="btn btn-primary btn-md importz">Read more
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-3">
          <div class="newclass">
            <h3>What I offer you </h3>
            A way to be happy
            <br>
            <br>
            <i class="fa fa-lightbulb-o fa-3x" aria-hidden="true"></i>
            <br>
            <br>
            <div class="btn btn-primary btn-md importz">Contact me
            </div>
          </div>
        </div>
        <br><br>
      </div>
    </div>
  </div>
  <div id="the-why" class="container-fluid visible-xs">
    <div class="why text-center">
      <div class="row">
        <div class="col-xs-12">
          <div class="newclass">
            <h3>What I do</h3>
            Being happy
            <br>
            <br>
            <i class="fa fa-question-circle fa-3x" aria-hidden="true"></i>
            <br>
            <br>
            <div class="btn btn-primary btn-xs importz">Read more
            </div>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="newclass">
            <h3>What I offer you </h3>
            A way to be happy
            <br>
            <br>
            <i class="fa fa-lightbulb-o fa-3x" aria-hidden="true"></i>
            <br>
            <br>
            <div class="btn btn-primary btn-xs importz">Contact me</div>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="newclass">
            <h3>What I do</h3>
            Being happy
            <br>
            <br>
            <i class="fa fa-question-circle fa-3x" aria-hidden="true"></i>
            <br>
            <br>
            <div class="btn btn-primary btn-xs importz">Read more
            </div>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="newclass">
            <h3>What I offer you </h3>
            A way to be happy
            <br>
            <br>
            <i class="fa fa-lightbulb-o fa-3x" aria-hidden="true"></i>
            <br>
            <br>
            <div class="btn btn-primary btn-xs importz">Contact me
            </div>
          </div>
        </div>
        <br><br>
      </div>
    </div>
  </div>
  <section id="testimonials">
    <div class="container wow fadeInUp">
      <div class="row">
        <div class="col-md-12">
          <h3 class="section-title">Ils ont aimé:</h3>
          <div class="section-title-divider">
          </div>
          <p class="section-description"></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <div class="profile">
            <div class="pic"><%= image_tag "blind.jpg" %>
            </div>
            <h4>Saul Goodman</h4>
            <span>Lawless Inc</span>
          </div>
        </div>
        <div class="col-md-9">
          <div class="quote">
            <b><img src="img/quote_sign_left.png" alt=""></b> <h4>"Proin iaculis purus consequat sem cure  digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper."</h4> <small><img src="img/quote_sign_right.png" alt=""></small>
          </div>
        </div>
      </div>
      <br><br>
      <div class="row">
        <div class="col-md-9">
          <div class="quote">
            <b><img src="img/quote_sign_left.png" alt=""></b> <h4> "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis architecto beatae."</h4> <small><img src="img/quote_sign_right.png" alt=""></small>
          </div>
        </div>
        <div class="col-md-3">
          <div class="profile">
           <div class="pic"><%= image_tag "sandrine-yoga-on-rocks.jpg" %>
           </div>
           <h4>Sara Parker</h4>
           <span>S.City</span>
         </div>
       </div>
     </div>
   </div>
  </section>
  <div class="banner-pellicule hidden-xs">
  </div>
  <div class="banner-pellicule-xs hidden-sm hidden-md hidden-lg">
  </div>
  <div>
  <div class="carousel js-flickity">
      <!-- images from unsplash.com -->
    <div class="carousel-cell">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/orange-tree.jpg" alt="orange tree" />
    </div>
    <div class="carousel-cell">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/submerged.jpg" alt="submerged" />
    </div>
    <div class="carousel-cell">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/look-out.jpg" alt="look-out" />
    </div>
    <div class="carousel-cell">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/one-world-trade.jpg" alt="One World Trade" />
    </div>
    <div class="carousel-cell">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/drizzle.jpg" alt="drizzle" />
    </div>
    <div class="carousel-cell">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/cat-nose.jpg" alt="cat nose" />
    </div>
    <div class="carousel-cell">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/contrail.jpg" alt="contrail" />
    </div>
    <div class="carousel-cell">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/golden-hour.jpg" alt="golden hour" />
    </div>
    <div class="carousel-cell">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/flight-formation.jpg" alt="flight formation" />
    </div>
    </div>
  </div>
  <div class="banner-pellicule hidden-xs">
  </div>
  <div class="banner-pellicule-xs hidden-sm hidden-md hidden-lg">
  </div>
  <section id="subscribe">
    <div class="container wow fadeInUp">
    <div class="row">
      <div class="col-md-8">
        <h3 class="subscribe-title">Free Stuff</h3>
        <p class="subscribe-text">Please, feel free to download</p>
      </div>
      <div class="col-md-4 subscribe-btn-container">
       <a class="subscribe-btn" href="#">Download</a>
     </div>
    </div>
  </div>
  </section>
  <div class="banner-parallax-3">
  </div>
</div>

app/views/pages/start_now.html.erb
<div class="banner-parallax-1">

</div>

app/views/posts/index.html.erb
<header class="blog1">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Le coin des lecteurs</h1>
        </div>
      <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Trouvez un article", class: "input-case" %>
    <%= submit_tag "Chercher", class: "btn btn-success" %>
    <% end %>
      </div>
      <%= link_to "Ecrire un nouvel article", new_post_path(@post), class: "btn btn-success btn-lg" %>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
<div class="row">
  <div class="col-xs-8">
    <div class="research">
    <% if @posts.present? %>
      <%= @posts %>
    <% else %>
      <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
    <% end %>
    </div>

  </div>
</div>
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">

      <div class="post-preview">
        <a >
          <% @posts.each do |post| %>
          <h2 class="post-title"><%= post.title %></h2>

        </a>

        <div>
          <h3 class="post-subtitle">
            <%= raw(post.body).truncate(158) %>
          </h3>
        </div>
        <p class="post-meta">Posted by
          <a href="#">Sandrine Loiret</a>
          on <%= post.created_at.strftime('%b %d, %Y') %> </p>

          <%= link_to "READ MORE", post_path(post), class: "btn btn-info" %>
          <%= link_to "Edit", edit_post_path(post), class: "btn btn-info" %>


          <br>

          <% end %>
        </div>

      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="disappear">
  <!-- <div class="menu-bar-fix hidden-sm hidden-xs"> -->
    <!-- <i class="fa fa-bars fa-2x dropdown-toggle" data-toggle="dropdown"></i> -->
    <!-- </div> -->
    <div id="disapp" class="navbar-kachinah hidden-sm hidden-xs">
      <!-- Logo -->
      <div class="logos">
        <%= link_to root_path, class: "navbar-kachinah-brand navbar-kachinah-item" do %>
        <%= image_tag "logo1.png" %>
        <% end %>
        <strong>
<!--     <%= link_to root_path, class: "navbar-kachinah-item navbar-kachinah-link sandrine-man" do %>
      <% "Sandrine Loiret" %>
      <% end %> -->
    </strong>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-kachinah-right hidden-xs hidden-sm">
    <!-- Links when logged in -->
    <%= link_to "ABOUT", about_path, class: "navbar-kachinah-item navbar-kachinah-link" %>
    <%= link_to "CONTACTEZ-MOI", new_contact_path, class: "navbar-kachinah-item navbar-kachinah-link" %>
    <%= link_to "COACHING", coaching_path, class: "navbar-kachinah-item navbar-kachinah-link" %>
    <%= link_to "E-BOOK", ebook_path, class: "navbar-kachinah-item navbar-kachinah-link" %>
    <%= link_to "BLOG", 'https://websize.me', class: "navbar-kachinah-item navbar-kachinah-link" %>
    <!-- Login link (when logged out) -->
    <!-- Avatar with dropdown menu -->
    <div class="navbar-kachinah-item wesh-right">
      <div class="dropdown" data-toggle="dropdown-toggle">
        <i class="menu-icon dropdown-toggle allo-right" data-toggle="dropdown" style="color: white; position: fixed; top: 25px; right: 4.5vw;"><span></span></i>
        <div class="dropdown-menu dropdown-menu-right navbar-kachinah-dropdown-menu" style="position: fixed; top: 20%">
          <div class="col-xs-12">
           <div class="" style="flex-direction: column;">
            <li class=""><h5 class=""><i class="fa fa-boo" aria-hidden="true"> </i> &nbsp  Take lessons</h5></li>
            <li class=""><h5 class=""><i style:"color: white;" class="fa fa-file-text-" aria-hidden="true"></i>&nbsp Dowload courses</h5></li>
            <li class=""><h5 class=""><i class="fa fa-envelope-" aria-hidden="true"></i>&nbsp Contactez-moi</h5></li>
            <li class=""><h5 class=""><i class="fa fa-info-circl" aria-hidden="true"></i>&nbsp Infos supp</h5></li>
            <li class=""><h5 class=""><i class="fa fa-file-text-" aria-hidden="true"></i>&nbsp Dowload courses</h5></li>
            <li class=""><h5 class=""><i class="fa fa-envelope-" aria-hidden="true"></i>&nbsp Contactez-moi</h5></li>
            <li class=""><h5 class=""><i class="fa fa-info-circl" aria-hidden="true"></i>&nbsp Infos supp</h5></li>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="navbar-kachinah hidden-sm hidden-md hidden-lg" style="opacity: 1; position: fixed;left: 70vw; width: 40vw;">
  <div class="logo-left" style="position: fixed; left: 10px;">
    <%= link_to root_path, class: "navbar-kachinah-brand navbar-kachinah-item" do %>
    <%= image_tag "logo1.png" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-kachinah-item  wesh-right ">
    <i class="menu-icon dropdown-toggle allo-right" data-toggle="dropdown" style="color: white; position: fixed; top: 25px; right: 4.5vw;"><span></span></i>
  </div>
  <ul class="dropdown-menu dropdown-menu-right navbar-kachinah-dropdown-menu">
    <li>
      <%= link_to "About", about_path, class: "navbar-kachinah-item navbar-kachinah-link" %>
    </li>
    <li>
      <%= link_to "Contactez-moi", new_contact_path, class: "navbar-kachinah-item navbar-kachinah-link" %>
    </li>
    <li>
      <%= link_to "Coaching", coaching_path, class: "navbar-kachinah-item navbar-kachinah-link" %>

    </li>
    <li>
      <%= link_to "e-book", ebook_path, class: "navbar-kachinah-item navbar-kachinah-link" %>

    </li>
    <li>
      <%= link_to "Blog", 'https://websize.me', class: "navbar-kachinah-item navbar-kachinah-link" %>

    </li>
    <li>

    </li>
  </ul>
</div>
<div class="navbar-kachinah hidden-xs hidden-md hidden-lg" style="opacity: 1; position: fixed;left: 85vw;">
  <div class="logo-left" style="position: fixed; left: 10px;">
    <%= link_to root_path, class: "navbar-kachinah-brand navbar-kachinah-item" do %>
    <%= image_tag "logo1.png" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-kachinah-item  mbars-right ">
    <div class="dropdown" data-toggle="dropdown">
     <i class="menu-icon dropdown-toggle allo-right" data-toggle="dropdown" style="color: white; position: fixed; top: 25px; right: 4.5vw;"><span></span></i>
     <ul class="dropdown-menu dropdown-menu-right navbar-kachinah-dropdown-menu" style=" right: -6.5vw; top: 0vh; height: 85vh;">
      <li>
        <%= link_to "About", about_path, class: "navbar-kachinah-item navbar-kachinah-link" %>

      </li>
      <li>
        <%= link_to "Contactez-moi", new_contact_path, class: "navbar-kachinah-item navbar-kachinah-link" %>

      </li>
      <li>
        <%= link_to "Coaching", coaching_path, class: "navbar-kachinah-item navbar-kachinah-link" %>

      </li>
      <li>
        <%= link_to "e-book", ebook_path, class: "navbar-kachinah-item navbar-kachinah-link" %>

      </li>
      <li>
        <%= link_to "Blog", 'https://websize.me', class: "navbar-kachinah-item navbar-kachinah-link" %>

      </li>
      <li>

      </li>
    </ul>
  </div>
</div>
</div>
</div>